import type { Metadata } from "next";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Header from "../components/Layout/Header";
import Footer from "../components/Layout/Footer";
import About from "@/components/Layout/AboutSection";
import Providers from '../components/Providers';
import { ConvexClientProvider } from "./ConvexClientProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <ConvexClientProvider>
          <Providers>
            <Header />
            {children}
            <About />
            <Footer />
          </Providers>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
